on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  allocate-kovan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        id: cache-deps
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}

      - name: Install Dependencies
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: yarn install

      - name: Run allocate-seigniorage.ts
        env: KOVAN_MNEMONIC: ${{ secrets.KOVAN_MNEMONIC }}
        run: yarn hardhat run --no-compile --network kovan scripts/allocate-seigniorage.ts
